spring:
  application:
    name: app-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ricardojes0412/config-test.git
          default-label: main
server:
  port: 7777
